Qulacs-Osaka/qulacs-visualizer

- .github/workflows/doc.yml
- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/index.rst
> API documentをBuildするCIのSetup

- CONTRIBUTING-en.md
- CONTRIBUTING-ja.md
> Add CONTRIBUTING

- .github/workflows/doc.yml
- CONTRIBUTING-en.md
- CONTRIBUTING-ja.md
- Makefile
- docs/Makefile
> Makefileの使い方の修正

- Makefile
- poetry.lock
- pyproject.toml
- qulacsvis/visualization/latex.py
- tests/conftest.py
- tests/latex_test.py
> pdflatexを呼び出すclassを作成した

- poetry.lock
- pyproject.toml
- qulacsvis/utils/latex.py
- qulacsvis/visualization/circuit_drawer.py
- tests/latex_test.py
> PDFからPNG画像を生成する機能を追加

- docs/Makefile
- pyproject.toml
- qulacsvis/__init__.py
- qulacsvis/utils/latex.py
- qulacsvis/visualization/__init__.py
- qulacsvis/visualization/circuit_drawer.py
- tests/latex_test.py
> プロジェクト構成を見直す

- qulacsvis/circuit_visualization.py
- qulacsvis/visualization/circuit_drawer.py
- qulacsvis/visualization/latex.py
- tests/circuit_drawer_test.py
make function to generate latex source
> 2 generate latex source

- qulacsvis/visualization/latex.py
> fix-generate-latex-source

- .github/workflows/ci.yml
- .github/workflows/doc.yml
- .github/workflows/wheel.yml
- poetry.lock
Close #42 
tagをpushすることによって、PyPIへ公開出来るようにします
> Publish to PyPI

- README.md
Close #25 
LaTeXの出力を使う場合の依存環境について記載しました。
> Describe the LaTeX environment

- qulacsvis/visualization/circuit_parser.py
手元で確認した分だと解消されました！
確認お願いします
テストケースは別の修正があるのでその時にまとめてやります
Closes #54
> fix circuit parser

- poetry.lock
- pyproject.toml
Close #70 
pillowのバージョンを9.1.0に更新しました
> Update pillow to 9.1.0

- pyproject.toml
> Release 0.2.2

- pyproject.toml
依存パッケージの更新を行いました。Qulacs>=0.5.0を利用できるようになったバージョンをリリースします。
> :tada: Release 0.3.1

- pyproject.toml
- #87 
dataclass_jsonを依存パッケージとして追加したバージョンを 0.3.2 としてリリースします
> :tada: Release 0.3.2

- doc/source/conf.py
- pyproject.toml
> :tada: Release 0.5.0

- doc/source/conf.py
- pyproject.toml
> :tada: Release 0.6.0

- doc/source/conf.py
- pyproject.toml
> :tada: Release 0.7.0

- doc/source/conf.py
- pyproject.toml
> :tada: Release 0.7.1

- qulacsvis/models/circuit.py
- qulacsvis/qulacs/circuit.py
- qulacsvis/visualization/circuit_drawer.py
- qulacsvis/visualization/circuit_parser.py
- qulacsvis/visualization/latex.py
- qulacsvis/visualization/matplotlib.py
- qulacsvis/visualization/text.py
- tests/generate/mpl_correct_data.py
- tests/mpl_circuit_drawer_test.py
- tests/test_utils.py
Hi 👋 
I wanted to use circuit drawers with input other than `qulacs.QuantumCircuit`, so I made following changes.
I would like to hear your opinion!
- Moved library-independent model definitions and construction defined in `circuit_parser` to `qulacsvis.models.circuit`.
- `CircuitData` is now a dataclass containing `qubit_count` and `layer_count` as well as gates in the circuit.
- Moved conversion from `qulacs.QuantumCircuit` to the library-independent `CircuitData` to `qulacsvis.qulacs.circuit.to_model()` function.
- Changed `MPLCircuitlDrawer` and `LatexSourceGenerator` to receive `CircuitData` instead of `qulacs.QuantumCircuit`
- In the `circuit_drawer()` function the `qulacs.QuantumCircuit` is converted to `CircuitData` before passed to those drawers.
Some notes:
- Since …
> Make matplotlib and latex drawers library-independent

- doc/source/conf.py
- pyproject.toml
> :tada: Release 0.7.2
